In [1]:
import pandas as pd
import numpy as np
import numpy as np
from sklearn.mixture import GaussianMixture

In [3]:
data = pd.read_csv('CRSP_hitorical_stock_daily_data.csv')
data.head()

/var/folders/nq/svc2nf551n74zpynk96y1b7w0000gn/T/ipykernel_31726/3347039667.py:1: DtypeWarning: Columns (5,6,9,18,19,20,22,24,49,57) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('CRSP_hitorical_stock_daily_data.csv')


PERMNO        date NAMEENDT  SHRCD  EXCHCD SICCD    NCUSIP TICKER  \
0   10026  2019-01-02      NaN   11.0     3.0  2052  46603210   JJSF   
1   10026  2019-01-03      NaN   11.0     3.0  2052  46603210   JJSF   
2   10026  2019-01-04      NaN   11.0     3.0  2052  46603210   JJSF   
3   10026  2019-01-07      NaN   11.0     3.0  2052  46603210   JJSF   
4   10026  2019-01-08      NaN   11.0     3.0  2052  46603210   JJSF   

                   COMNAM SHRCLS  ... CFACPR  CFACSHR    OPENPRC  NUMTRD  \
0  J & J SNACK FOODS CORP    NaN  ...    1.0      1.0  143.42000  1648.0   
1  J & J SNACK FOODS CORP    NaN  ...    1.0      1.0  140.60001  1272.0   
2  J & J SNACK FOODS CORP    NaN  ...    1.0      1.0  144.19000  1068.0   
3  J & J SNACK FOODS CORP    NaN  ...    1.0      1.0  144.37000  1276.0   
4  J & J SNACK FOODS CORP    NaN  ...    1.0      1.0  146.14999   923.0   

        RETX    vwretd    vwretx    ewretd    ewretx    sprtrn  
0  -0.024829  0.001796  0.001791  0.017126  0.017105  0.001269  
1   0.014326 -0.021043 -0.021229 -0.009454 -0.009493 -0.024757  
2   0.012725  0.033410  0.033409  0.030804  0.030780  0.034336  
3   0.003935  0.009202  0.009196  0.016144  0.016133  0.007010  
4   0.022626  0.010269  0.010248  0.010358  0.010339  0.009695  

[5 rows x 63 columns]

In [4]:
data.shape

(10795583, 63)

In [6]:
data.groupby('PERMNO').size()

PERMNO
10026    1258
10028    1258
10032    1258
10044    1258
10051     947
         ... 
93426    1258
93427    1258
93429    1258
93434    1258
93436    1258
Length: 12295, dtype: int64

In [7]:
data_sub = data[data['PERMNO'] == 10026]
data_sub

PERMNO        date NAMEENDT  SHRCD  EXCHCD SICCD    NCUSIP TICKER  \
0      10026  2019-01-02      NaN   11.0     3.0  2052  46603210   JJSF   
1      10026  2019-01-03      NaN   11.0     3.0  2052  46603210   JJSF   
2      10026  2019-01-04      NaN   11.0     3.0  2052  46603210   JJSF   
3      10026  2019-01-07      NaN   11.0     3.0  2052  46603210   JJSF   
4      10026  2019-01-08      NaN   11.0     3.0  2052  46603210   JJSF   
...      ...         ...      ...    ...     ...   ...       ...    ...   
1253   10026  2023-12-22      NaN   11.0     3.0  2052  46603210   JJSF   
1254   10026  2023-12-26      NaN   11.0     3.0  2052  46603210   JJSF   
1255   10026  2023-12-27      NaN   11.0     3.0  2052  46603210   JJSF   
1256   10026  2023-12-28      NaN   11.0     3.0  2052  46603210   JJSF   
1257   10026  2023-12-29      NaN   11.0     3.0  2052  46603210   JJSF   

                      COMNAM SHRCLS  ... CFACPR  CFACSHR    OPENPRC  NUMTRD  \
0     J & J SNACK FOODS CORP    NaN  ...    1.0      1.0  143.42000  1648.0   
1     J & J SNACK FOODS CORP    NaN  ...    1.0      1.0  140.60001  1272.0   
2     J & J SNACK FOODS CORP    NaN  ...    1.0      1.0  144.19000  1068.0   
3     J & J SNACK FOODS CORP    NaN  ...    1.0      1.0  144.37000  1276.0   
4     J & J SNACK FOODS CORP    NaN  ...    1.0      1.0  146.14999   923.0   
...                      ...    ...  ...    ...      ...        ...     ...   
1253  J & J SNACK FOODS CORP    NaN  ...    1.0      1.0  167.80000  2563.0   
1254  J & J SNACK FOODS CORP    NaN  ...    1.0      1.0  167.96001  2302.0   
1255  J & J SNACK FOODS CORP    NaN  ...    1.0      1.0  168.84000  3087.0   
1256  J & J SNACK FOODS CORP    NaN  ...    1.0      1.0  167.39000  2510.0   
1257  J & J SNACK FOODS CORP    NaN  ...    1.0      1.0  168.46001  2180.0   

           RETX    vwretd    vwretx    ewretd    ewretx    sprtrn  
0     -0.024829  0.001796  0.001791  0.017126  0.017105  0.001269  
1      0.014326 -0.021043 -0.021229 -0.009454 -0.009493 -0.024757  
2      0.012725  0.033410  0.033409  0.030804  0.030780  0.034336  
3      0.003935  0.009202  0.009196  0.016144  0.016133  0.007010  
4      0.022626  0.010269  0.010248  0.010358  0.010339  0.009695  
...         ...       ...       ...       ...       ...       ...  
1253   0.006903  0.002440  0.002372  0.007676  0.007387  0.001660  
1254   0.003815  0.005218  0.005199  0.009674  0.009299  0.004232  
1255  -0.005880  0.001995  0.001807  0.005276  0.004907  0.001430  
1256   0.006392 -0.000108 -0.000295  0.002042  0.001428  0.000370  
1257  -0.007836 -0.004045 -0.004084 -0.007480 -0.007546 -0.002826  

[1258 rows x 63 columns]

In [12]:
# get all the numerical columns
X = data_sub.select_dtypes(include=[np.number])
X = X.dropna(axis=1)
X

PERMNO  SHRCD  EXCHCD     NAICS  PERMCO  ISSUNO  HEXCD      BIDLO  \
0      10026   11.0     3.0  311821.0    7976   10433      3  139.12000   
1      10026   11.0     3.0  311821.0    7976   10433      3  140.27000   
2      10026   11.0     3.0  311821.0    7976   10433      3  143.16479   
3      10026   11.0     3.0  311821.0    7976   10433      3  142.83000   
4      10026   11.0     3.0  311821.0    7976   10433      3  145.50000   
...      ...    ...     ...       ...     ...     ...    ...        ...   
1253   10026   11.0     3.0  311930.0    7976   10433      3  167.25999   
1254   10026   11.0     3.0  311930.0    7976   10433      3  166.69000   
1255   10026   11.0     3.0  311930.0    7976   10433      3  167.33000   
1256   10026   11.0     3.0  311930.0    7976   10433      3  167.33000   
1257   10026   11.0     3.0  311930.0    7976   10433      3  167.06000   

          ASKHI        PRC  ...   SHROUT  CFACPR  CFACSHR    OPENPRC  NUMTRD  \
0     144.03999  141.00000  ...  18774.0     1.0      1.0  143.42000  1648.0   
1     145.91000  143.02000  ...  18774.0     1.0      1.0  140.60001  1272.0   
2     147.36501  144.84000  ...  18774.0     1.0      1.0  144.19000  1068.0   
3     147.87000  145.41000  ...  18774.0     1.0      1.0  144.37000  1276.0   
4     149.30231  148.70000  ...  18774.0     1.0      1.0  146.14999   923.0   
...         ...        ...  ...      ...     ...      ...        ...     ...   
1253  169.29500  167.74001  ...  19342.0     1.0      1.0  167.80000  2563.0   
1254  169.32001  168.38000  ...  19342.0     1.0      1.0  167.96001  2302.0   
1255  169.20000  167.39000  ...  19342.0     1.0      1.0  168.84000  3087.0   
1256  171.03999  168.46001  ...  19342.0     1.0      1.0  167.39000  2510.0   
1257  168.89999  167.14000  ...  19342.0     1.0      1.0  168.46001  2180.0   

        vwretd    vwretx    ewretd    ewretx    sprtrn  
0     0.001796  0.001791  0.017126  0.017105  0.001269  
1    -0.021043 -0.021229 -0.009454 -0.009493 -0.024757  
2     0.033410  0.033409  0.030804  0.030780  0.034336  
3     0.009202  0.009196  0.016144  0.016133  0.007010  
4     0.010269  0.010248  0.010358  0.010339  0.009695  
...        ...       ...       ...       ...       ...  
1253  0.002440  0.002372  0.007676  0.007387  0.001660  
1254  0.005218  0.005199  0.009674  0.009299  0.004232  
1255  0.001995  0.001807  0.005276  0.004907  0.001430  
1256 -0.000108 -0.000295  0.002042  0.001428  0.000370  
1257 -0.004045 -0.004084 -0.007480 -0.007546 -0.002826  

[1258 rows x 23 columns]

In [37]:
X.columns

Index(['PERMNO', 'SHRCD', 'EXCHCD', 'NAICS', 'PERMCO', 'ISSUNO', 'HEXCD',
       'BIDLO', 'ASKHI', 'PRC', 'VOL', 'BID', 'ASK', 'SHROUT', 'CFACPR',
       'CFACSHR', 'OPENPRC', 'NUMTRD', 'vwretd', 'vwretx', 'ewretd', 'ewretx',
       'sprtrn'],
      dtype='object')

# Gaussian Mixture Model (GMM)

In [13]:

gm = GaussianMixture(n_components=2, random_state=0).fit(X)
gm.means_


/Users/tush/miniconda3/envs/finance/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but GaussianMixture was fitted with feature names
  warnings.warn(


ValueError: X has 2 features, but GaussianMixture is expecting 23 features as input.

In [15]:
gm.means_.shape

(2, 23)

In [29]:
X_reduced = gm.predict_proba(X.to_numpy())
X_reduced

/Users/tush/miniconda3/envs/finance/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but GaussianMixture was fitted with feature names
  warnings.warn(


array([[2.65879784e-01, 7.34120216e-01],
       [5.62704173e-02, 9.43729583e-01],
       [5.45429255e-01, 4.54570745e-01],
       ...,
       [9.99966946e-01, 3.30543052e-05],
       [9.99047259e-01, 9.52741381e-04],
       [9.99988485e-01, 1.15145956e-05]])

# LDA (LSI)

In [30]:
from sklearn.decomposition import PCA

In [31]:
pca = PCA(n_components=2)
X_reduced_pca = pca.fit_transform(X)
X_reduced_pca

array([[ 22318.06872434,   1198.91078213],
       [ -6178.1831749 ,   1313.09424862],
       [ -2278.22998296,   1551.20063872],
       ...,
       [-26393.87358957,   -740.0717356 ],
       [  1667.61325516,     88.0571622 ],
       [-39149.68943983,     44.4265676 ]])

# KMeans

In [32]:
from sklearn.cluster import KMeans

In [33]:
X_reduced_kmeans = KMeans(n_clusters=2, random_state=0, n_init="auto").fit_transform(X)
X_reduced_kmeans

array([[ 29080.75483777, 339448.06605737],
       [  1440.75883066, 367944.49635119],
       [  4725.01846543, 364045.18877119],
       ...,
       [ 19671.2961335 , 388160.74185537],
       [  8411.52435083, 360097.6824653 ],
       [ 32413.7366385 , 400914.99841876]])

# LDA

In [39]:
from sklearn.decomposition import LatentDirichletAllocation as LDA

In [40]:
X_reduced_lda = LDA().fit_transform(X)
X_reduced_lda

ValueError: Negative values in data passed to LatentDirichletAllocation.fit